# Generated by Django 5.0 on 2023-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
