# Generated by Django 5.0 on 2024-01-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_question_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
